# Generated by Django 3.2.6 on 2021-10-25 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20211025_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
