# Generated by Django 3.2.6 on 2021-09-12 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_auto_20210912_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.TextField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='postcode',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='town',
            field=models.TextField(max_length=255),
        ),
    ]
